### PR TITLE
Sused upඞ

### PR DESCRIPTION
**Pull request by cozerCode**
ඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞ

### CODE REVIEW

**Review by Commensalism1997 — CHANGES_REQUESTED** [review]
bad!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by cozerCode** [comment]
bro wtf

**Comment by Commensalism1997** [comment]
amogus

**Comment by Commensalism1997** [comment]
amogus

**Review by Deltara3 — CHANGES_REQUESTED** [review]
The new line escape character is necessary.

**Review by Deltara3 — CHANGES_REQUESTED** [review]
This would be fine as an alternate file, not a replacement to the base one.

**Review by Commensalism1997 — COMMENTED** [review]
zamn this is literally brainfuck but amogus

**Pull request closed without merging**
